// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDyrNGQ80VKOXv8bKN9_aLooyrvLfNGWQ',
    appId: '1:1057441886658:web:1bd4affef36ce45f69a65b',
    messagingSenderId: '1057441886658',
    projectId: 'hrm-firebase-fb796',
    authDomain: 'hrm-firebase-fb796.firebaseapp.com',
    storageBucket: 'hrm-firebase-fb796.appspot.com',
    measurementId: 'G-HW0FYJ38DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmQbXsSEluezI6mk9HyN8r1-Ht2EkPI-0',
    appId: '1:1057441886658:android:441294d6ea7da24e69a65b',
    messagingSenderId: '1057441886658',
    projectId: 'hrm-firebase-fb796',
    storageBucket: 'hrm-firebase-fb796.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeVVNmofNsus2ff6jepIuME9sfnF9Niw',
    appId: '1:1057441886658:ios:114af9531bad038c69a65b',
    messagingSenderId: '1057441886658',
    projectId: 'hrm-firebase-fb796',
    storageBucket: 'hrm-firebase-fb796.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeVVNmofNsus2ff6jepIuME9sfnF9Niw',
    appId: '1:1057441886658:ios:114af9531bad038c69a65b',
    messagingSenderId: '1057441886658',
    projectId: 'hrm-firebase-fb796',
    storageBucket: 'hrm-firebase-fb796.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
